package com.digitalforce.datingapp.constants;

public class DatingConstants {

    //twitter credential
    public static String CONSUMER_KEY = "r1QLSq4zwdBsH8DbD7KgalsMs";
    public static String CONSUMER_SECRET = "3Dss6xBJsr2BiOKU9Q1SwerTMB5Dv76meNBld74JBXgYRxxgAA";

	//twitter credential KMD
	/*public static String CONSUMER_KEY = "Kziz8AV7MPrYUobiamoAyCbmc";
	public static String CONSUMER_SECRET = "pBePZht3sGopVIE3ZZi1xAM09cOHWh4C3tZL4qb6nxP6okYFwD";*/


	
	//manage flow for t&c
	public static int TCACTION = 111;

            /*Hex Opacity Values

            100% — FF
            95% — F2
            90% — E6
            85% — D9
            80% — CC
            75% — BF
            70% — B3
            65% — A6
            60% — 99
            55% — 8C
            50% — 80
            45% — 73
            40% — 66
            35% — 59
            30% — 4D
            25% — 40
            20% — 33
            15% — 26
            10% — 1A
            5% — 0D
            0% — 00*/

    public static final String HEADER_TEXT_1 = "This is a legal agreement (\"Agreement\") between you and Yental Empire, LLC., a Delaware limited liability company (the \"Company\"), which may be contacted at 2885 Sanford Ave SW #28946, Grandville, MI 49418 USA. By accessing the Company's N2HIM smartphone application, (the “App”) and using any of the Services (as defined below) accessible through the App, you agree to, and are bound by, the terms and conditions of this Agreement for as long as you continue to use the Service. The Company services consist of the following, without limitation: a service for single people seeking same-sex matches (the “Service”) and premium services offered by or on behalf of the Company (“Premium Services”) (collectively, the “Services”). IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT, DO NOT USE THE SERVICES. The Company may offer additional services or revise the Services, at its discretion, and this Agreement will apply to all additional services or revised Services. Your use of, or participation in, certain services may be subject to additional terms, and such terms will be either listed in this Agreement or will be presented to you for your acceptance when you sign up to use such services.";
    public static final String HEADER_TEXT_2 = "Please review this Agreement carefully, including the Arbitration provision in Section XX, which describes how Disputes (as defined below) will be resolved between us, and that no class actions may be brought under this Agreement.";
    public static final String HEADER_TEXT_3 = "This Agreement is subject to change by the Company in its sole discretion from time to time, and any such change will be posted on the App. Your continued use of the Service after the posting of revisions to this Agreement will constitute your acceptance of such revisions. Please consult the end of this Agreement to determine when the Agreement was last revised.";

    public static final String ELIGIBILITY_TEXT_1 = "1. Minimum Age. You must be at least 18 years old to use the App (or the age of majority in your jurisdiction, if it is older) or register for the Services. By using the Services, you represent and warrant that you are at least 18 years old.";
    public static final String ELIGIBILITY_TEXT_2 = "2. Relationship Status. By requesting to use, registering to use, or using the Service, you represent and warrant that you are not currently married or in another legally recognized relationship such as a New Jersey civil union or a California registered domestic partnership. If you are separated, but your relationship has not yet been dissolved as a matter of law, you may not register to use, or use the Service.";
    public static final String ELIGIBILITY_TEXT_3 = "3. Criminal History. By registering to use, and/or using the Services, you represent and warrant that you have never been convicted of a felony and are not required to register as a sex offender with any government entity. N2HIM DOES NOT CURRENTLY CONDUCT CRIMINAL BACKGROUND SCREENINGS ON ITS MEMBERS. However, the Company reserves the right to conduct any criminal background check, at any time and using available public records, to confirm your compliance partner with this\n" +
            "subsection.BY AGREEING TO THESE TERMS AND CONDITIONS, YOU HEREBY AUTHORIZE ANY SUCH CHECK.";

    public static final String TC_SERVICE_TEXT = "As a user of the App or a user registered to use any of the Services (a \"Registered User\"), you agree to the following:";
    public static final String SERVICEABILITY_TEXT_1 = "1. Exclusive Use. Your account is for your personal use only. You may not authorize others to use your account, and you may not assign or otherwise transfer your account to any other person or entity. You acknowledge that the Company is not responsible for third party access to your account that results from theft or misappropriation of your user names and passwords.";
    public static final String SERVICEABILITY_TEXT_2 = "2. Information Submitted. You are solely responsible for, and assume all liability regarding, (i) the information and content you contribute to the Service; (ii) the information and content you post, transmit, publish, or otherwise make available (hereinafter “post”) through the Service; and (iii) your interactions with other Registered Users through the Service. In addition to sharing your information with your matches, we may allow your matches to share your profile information with members of their social network(s).";
    public static final String SERVICEABILITY_TEXT_3 = "3. Risk Assumption and Precautions. You assume all risk when using the Service, including but not limited to all of the risks associated with any online or offline interactions with others, including dating. You agree to take all necessary precautions when meeting individuals through the Service.";
    public static final String SERVICEABILITY_TEXT_4 = "4. No Guarantees. The Company may not be able to provide matches for everyone seeking to use its services. Further, the Company makes no guarantees as to number or frequency of matches through the Service, or to such matches' ability, desire or criteria to communicate with any user. You understand that the Company makes no guarantees, either express or implied, regarding your ultimate compatibility with individuals you meet through the Service or as to the conduct of such individuals.";
    public static final String SERVICEABILITY_TEXT_5 = "5. Reporting of Violations. You will promptly report to the Company any violation of the Agreement by others, including but not limited to, Registered Users.";
    public static final String SERVICEABILITY_TEXT_6 = "6. Content Removal. The Company reserves the right, but has no obligation, to monitor the information or material you submit to the Service or post in the public areas of the Service. The Company will have the right to remove any such information or material that in its sole opinion violates, or may violate, any applicable law or either the letter or spirit of this Agreement or upon the request of any third party. The Company further reserves the right to remove matches previously delivered to you, in its reasonable discretion, in order to assure that you have a quality experience on the App.";
    public static final String SERVICEABILITY_TEXT_7 = "7. Posting and Communication Restrictions. You will not post on the Service, transmit to other users, communicate any content (or links thereto), or otherwise engage in any activity on the Site or through the Services, that:";
    public static final String SERVICEABILITY_TEXT_8 = "8. No False Information. You will not provide inaccurate, misleading or false information to the Company or to any other user. If information provided to the Company or another user subsequently becomes inaccurate, misleading or false, you will promptly notify the Company of such change.";
    public static final String SERVICEABILITY_TEXT_9 = "9. No Advertising or Commercial Solicitation. You will not advertise or solicit any user to buy or sell any products or services through the App or Services. You may not transmit any chain letters, junk or spam e-mail to other users. Further, you will not use any information obtained from the Services in order to contact, advertise to, solicit, or sell to any user without their prior explicit consent. If you breach the terms of this subsection and send or post unsolicited bulk email, “spam” or other unsolicited communications of any kind through the Services, you acknowledge that you will have caused substantial harm to the Company, but that the amount of such harm would be extremely difficult to ascertain. As a reasonable estimation of such harm, you agree to pay the Company $50 for each such unsolicited communication you send through the Services.";
    public static final String SERVICEABILITY_TEXT_10 = "10. Unique and Bona Fide Profile. As a Registered User of the Service, you will create only one unique profile. In addition, your use of the Service must be for bona fide relationship-seeking purposes in order to maintain the integrity of the Service (for example, you may not become a Registered User solely to compile a report of compatible singles in your area, or to write an article or school research paper).";
    public static final String SERVICEABILITY_TEXT_11 = "11. Availability for Matching. Not all registered users are available for matching. From time to time, the Company may create test profiles in order to monitor the operation of the Service.";
    public static final String SERVICEABILITY_TEXT_12 = "12. No Harassment of Employees or Agents. You will not harass, annoy, intimidate or threaten any Company employees or agents engaged in providing any portion of the Services to you.";
    public static final String SERVICEABILITY_TEXT_13 = "13. Social Media. We may provide you the option to connect your N2HIM account to your account on some social networking sites (such as via Facebook Connect) for the purpose of logging in, uploading information or enabling certain features on the Service. When enabling this feature, we will disclose to you the information we collect from the connected social networking site, and will use such information in compliance with our Privacy Policy. Once connected, some of your matches may also be able to see information about your social network, such as the size of your network and your friends, including common friends. By connecting your N2HIM account to your account on any social networking site, you hereby consent to the continuous release of information about you to N2HIM. We will not send any of your N2HIM account information to the connected social networking site without first disclosing that to you. You can always disconnect the accounts via your N2HIM Account Settings page. Each social network\n" +
            "may further allow you to set privacy controls around your information on their system, and the Company’s collection of information will always follow such controls and permissions. This feature is subject to continuous change and improvement by us and each social networking site involved, and therefore the available features and shared information are subject to change without notice to you.";

    public static final String PROPRIETARY_1 = "1. Ownership of Proprietary Information. You hereby acknowledge and agree that the Company is the owner of highly valuable proprietary information, including without limitation, the patented compatibility matching system, compatibility profiles, and relationship questionnaires (collectively, \"Confidential Information\"). The Company owns and hereby retains all proprietary rights in the Services and the App, including but not limited to, all Confidential Information.";
    public static final String PROPRIETARY_2 = "2. No Use of Confidential Information. You will not post, copy, modify, transmit, disclose, show in public, create any derivative works from, distribute, make commercial use of, or reproduce in any way any (i) Confidential Information or (ii) other copyrighted material, trademarks, or other proprietary information accessible via the Service, without first obtaining the prior written consent of the owner of such proprietary rights.";
    public static final String PROPRIETARY_3 = "3. Other Users' Information. Other Registered Users may post copyrighted information, which has copyright protection whether or not it is identified as copyrighted. You agree that you will not copy, modify, publish, transmit, distribute, perform, display, commercially use, or sell any Company or third party proprietary information available via the Services or the App.";
    public static final String PROPRIETARY_4 = "4. License to Posted or Accessed Content. By posting information or content to any profile pages or public area of the Service, or making it accessible to us by linking your N2HIM account to any of your social network accounts (e.g. via Facebook Connect), you automatically grant, and you represent and warrant that you have the right to grant, to the Company and its users, an irrevocable, perpetual, non-exclusive, fully-paid, worldwide license to use, reproduce, publicly perform, publicly display and distribute such information and content, and to prepare derivative works of, or incorporate into other works, such information and content, and to grant and authorize sub-licenses of the foregoing. From time to time, we may create, test or implement new features or programs on the App in which you may voluntarily choose to participate, or may be part of a test group with special access, in accordance with the additional terms and conditions of such features or programs. By your participation in such features or programs, you grant us the rights stated in this subsection in connection with the additional terms and conditions (if any) of such features or programs.";

    public static final String USE_1 = "1. Disclosure by Law. You acknowledge and agree that the Company may disclose information you provide if required to do so by law, at the request of a third party, or if we, in our sole discretion, believe that disclosure is reasonable to (1) comply with the law, requests or orders from law enforcement, or any legal process (whether or not such disclosure is required by applicable law); (2) protect or defend the Company’s, or a third party’s, rights or property; or (3) protect someone’s health or safety, such as when harm or violence against any person (including the user) is threatened.";
    public static final String USE_2 = "2. Disclosure to Protect Abuse Victims. Notwithstanding any other provision of this Agreement, the Company reserves the right, but has no obligation, to disclose any information that you submit to the Services, if in its sole opinion, the Company suspects or has reason to suspect, that the information involves a party who may be the victim of abuse in any form. Abuse may include, without limitation, elder abuse, child abuse, spousal abuse, neglect, or domestic violence. Information may be disclosed to authorities that the Company, in its sole discretion, deems appropriate to handle such disclosure. Appropriate authorities may include, without limitation, law enforcement agencies, child protection agencies, or court officials. You hereby acknowledge and agree that the Company is permitted to make such disclosure.";
    public static final String USE_3 = "3. Use of Anonymous Information for Research. By using the Services, you agree to allow the Company to anonymously use the information from you and your experiences through the Services to continue its research into successful relationships and to improve the Services. This research, conducted by psychologists and behavior research scientists, may be published in academic journals. However, all of your responses will be anonymous, and we will not publish research containing your personal identifying information.";

    public static final String SPONSORS = "The Services may contain links to web sites of third-parties, including without limitation, advertisers, which are not under the control of the Company, and the Company is not responsible for the content of any linked site or any link contained in a linked site, or any changes or updates to such web sites. The Company provides these links to you only as a convenience, and the inclusion of any link does not imply that the Company endorses or accepts any responsibility for the content on such third-party web site. Your correspondence or business dealings with, or participation in promotions of, advertisers or sweepstakes sponsors found on or through the Services (including payment and delivery of related goods or services, any personal information or opt-in contact information voluntarily given to advertisers and sweepstake sponsors, and any other terms, conditions, warranties or representations associated with such dealings) are solely between you and such advertiser or sweepstakes sponsor. You agree that the Company will not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings, including the sharing of the information you supply to the Company with advertisers or sweepstakes sponsors, or as the result of the presence of such advertisers on the Services.";

    public static final String DISCLAIMER_1 = "1. No Warranties. THIS SECTION WILL APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW. THE COMPANY PROVIDES THE SERVICES ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS AND GRANTS NO WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE WITH RESPECT TO THE SERVICES OR THE APP (INCLUDING ALL INFORMATION CONTAINED THEREIN), INCLUDING ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. THE COMPANY DOES NOT WARRANT THAT YOUR USE OF THE SERVICES WILL BE SECURE, UNINTERRUPTED, ALWAYS AVAILABLE, ERROR-FREE OR WILL MEET YOUR REQUIREMENTS, OR THAT ANY DEFECTS IN THE SERVICES WILL BE CORRECTED. THE COMPANY DISCLAIMS LIABILITY FOR, AND NO WARRANTY IS MADE WITH RESPECT TO, THE CONNECTIVITY AND AVAILABILITY OF THE SERVICES.";
    public static final String DISCLAIMER_2 = "2. Third Party Content. Opinions, advice, statements, offers, or other information or content made available through the Services, but not directly by the Company, are those of their respective authors, and should not necessarily be relied upon. Such authors are solely responsible for such content. THE COMPANY DOES NOT: (i) GUARANTEE THE ACCURACY, COMPLETENESS OR USEFULNESS OF ANY INFORMATION PROVIDED ON THE SERVICES, OR (ii) ADOPT, ENDORSE OR ACCEPT RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, ADVICE, OR STATEMENT MADE BY ANY PARTY OTHER THAN THE COMPANY. UNDER NO CIRCUMSTANCES WILL THE COMPANY BE RESPONSIBLE FOR ANY LOSS OR DAMAGE RESULTING FROM ANYONE’S RELIANCE ON INFORMATION OR OTHER CONTENT POSTED ON THE SERVICES, OR TRANSMITTED TO OR BY ANY USERS.";
    public static final String DISCLAIMER_3 = "3. Beta Features. From time to time, the Company may offer new \"beta\" features or tools with which its users may experiment on the Services. Such features or tools are offered solely for experimental purposes and without any warranty of any kind, and may be modified or discontinued at the Company's sole discretion. The provisions of this Disclaimer of Warranty section apply with full force to such features or tools.";

    public static final String LIABILITY_1 = "1. Incidental Damages and Aggregate Liability. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL THE COMPANY BE LIABLE FOR ANY INCIDENTAL, SPECIAL, CONSEQUENTIAL OR INDIRECT DAMAGES ARISING OUT OF OR RELATING TO THE USE OR INABILITY TO USE THE SERVICES, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OR CORRUPTION OF DATA OR PROGRAMS, SERVICE INTERRUPTIONS AND PROCUREMENT OF SUBSTITUTE SERVICES, EVEN IF THE COMPANY KNOWS OR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES WILL THE COMPANY’S AGGREGATE LIABILITY, IN ANY\n" +
            "FORM OF ACTION WHATSOEVER IN CONNECTION WITH THIS AGREEMENT OR THE USE OF THE SERVICES, EXCEED THE AMOUNT OF US$25.00 OR ITS EQUIVALENT.";
    public static final String LIABILITY_2 = "2. No Liability for non-Company Actions. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL THE COMPANY BE LIABLE FOR ANY DAMAGES WHATSOEVER, WHETHER DIRECT, INDIRECT, GENERAL, SPECIAL, COMPENSATORY, CONSEQUENTIAL, AND/OR INCIDENTAL, ARISING OUT OF OR RELATING TO THE CONDUCT OF YOU OR ANYONE ELSE IN CONNECTION WITH THE USE OF THE SERVICES, INCLUDING WITHOUT LIMITATION, BODILY INJURY, EMOTIONAL DISTRESS, AND/OR ANY OTHER DAMAGES RESULTING FROM COMMUNICATIONS OR MEETINGS WITH OTHER REGISTERED USERS OF THE SERVICES. THIS INCLUDES ANY CLAIMS, LOSSES OR DAMAGES ARISING FROM THE CONDUCT OF USERS WHO HAVE REGISTERED UNDER FALSE PRETENSES OR WHO ATTEMPT TO DEFRAUD OR HARM YOU.";
    public static final String LIABILITY_3 = "3. Information Verification. The Company and its contractors may use various ways of verifying information that users have provided. However, none of those ways are perfect, and you agree that the Company and its contractors will have no liability to you arising from any incorrectly verified information.";

    public static final String INDEMNIFICATION = "You agree to indemnify, defend and hold harmless the Company, its subsidiary and parent companies, and each of their officers, directors, employees, agents and related third parties, for any losses, costs, liabilities and expenses (including reasonable attorneys’ fees) relating to or arising out of any third party claim that (a) your use of or inability to use the App or Services, (b) any user postings made by you, (c) your violation of any terms of this Agreement or your violation of any rights of a third party, or (d) your violation of any applicable laws, rules or regulations. The Company reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with the Company in asserting any available defenses.";
    public static final String TERMINATION = "This Agreement will become effective upon your acceptance of the Agreement by your use of the Site or the Services and will remain in effect in perpetuity unless terminated hereunder. Either you or the Company may terminate this Agreement at any time, for any reason or no reason, without explanation, effective upon sending written notice to the other party. The Company reserves the right to immediately suspend or terminate your access to any of the Services, without notice, for any reason or no reason. We also reserve the right to remove your account information or data from our Services and any other records at any time at our sole discretion. In the event your access to any of the Services is suspended due to the breach of this Agreement, you agree that all fees then paid to the Company by you will be nonrefundable and\n" +
            "all outstanding or pending payments will immediately be due. You may terminate your account by following the steps in the applicable section under \"Cancellations\" below, or by sending a notice of cancellation to: Yental Empire LLC., Attn: Yental Empire Cancellations, 2885 Sanford Ave SW #28946, Grandville, MI 49418 USA. Following any termination of any Registered User's use of the Service, the Company reserves the right to send a notice thereof to other Registered Users which whom you have corresponded.";

    public static final String ARBITRATION_1 = "1. Arbitration of Disputes. You and the Company agree that any disputes arising out of or related to the App, the Services, this Agreement and/or any policies or practices of the Company (a “Dispute”) will be subject to FINAL AND BINDING ARBITRATION as set forth in this section, and may only be resolved through an individual arbitration governed by the Federal Arbitration Act, to the maximum extent permitted by applicable law. The only exceptions to this agreement to arbitrate Disputes are claims of infringement or misappropriation of the Company’s copyright, patent, trade secret, trademark, service mark, trade dress or other intellectual property or proprietary rights, which the Company may elect to have resolved by means other than arbitration. Notwithstanding the above, the Company is always interested in attempting to resolve any Disputes by amicable and informal means, and we encourage you to contact us before resorting to arbitration. YOU AND THE COMPANY AGREE THAT WE ARE EACH GIVING UP OUR RIGHT TO GO TO COURT in connection with any Dispute, and that our rights will be determined by a NEUTRAL ARBITRATOR, NOT A JUDGE OR JURY.";
    public static final String ARBITRATION_2 = "2. No Class Actions. YOU AND THE COMPANY ACKNOWLEDGE THAT NEITHER OF US WILL BRING OR PARTICIPATE IN ANY CLASS ACTION OR OTHER CLASS PROCEEDING IN CONNECTION WITH ANY DISPUTE WITH THE OTHE PARTY. Further, neither you nor the Company agrees to class arbitration or any arbitration where a person brings a dispute as a representative of other person(s).";
    public static final String ARBITRATION_3 = "3. Arbitration Procedure. If the parties are unable to resolve a Dispute by informal means, the arbitration of Disputes will be administered by the American Arbitration Association (AAA), a non-profit organization not affiliated with the Company, in accordance with its Commercial Arbitration Rules, and if deemed appropriate by the arbitrator, the Supplementary Procedures for Consumer-Related Disputes.";
    public static final String ARBITRATION_4 = "4. Enforcement Any proceeding to enforce this arbitration agreement may be brought in any court of competent jurisdiction.";
    public static final String ARBITRATION_5 = "5. Limitation of Time Period to Commence a Dispute. Regardless of any statute or law to the contrary, and to the maximum extent permitted by applicable law, any Dispute must be filed within one (1) year after the date in which the incident giving rise to the Dispute occurred. Failure to file an arbitration claim as described above within the applicable limitations period constitutes a waiver of such claim and serves as complete bar to any claim based on any Dispute.";

    public static final String GENERAL_PROVISIONS = "Right to Seek Injunction Violation of this Agreement may cause the Company irreparable harm, and therefore agree that the Company will be entitled to seek extraordinary relief in court, including but not limited to temporary restraining orders, preliminary injunctions and permanent injunctions without the necessity of posting a bond or other security, in addition to and without prejudice to any other rights or remedies that the Company may have for a breach of this Agreement.";

    public static final String DIGITAL_MILLENNIUM = "If you believe that your copyrighted work has been copied in a way that constitutes copyright infringement and is accessible on the App, please notify the Company’s copyright agent, as set forth in the Digital Millennium Copyright Act of 1998 (DMCA). For your complaint to be valid under the DMCA, you must provide the following information in writing:";

    public static final String DIGITAL_MILLENIUM_1 = "1. An electronic or physical signature of a person authorized to act on behalf of the copyright owner;";
    public static final String DIGITAL_MILLENIUM_2 = "2. Identification of the copyrighted work that you claim is being infringed;";
    public static final String DIGITAL_MILLENIUM_3 = "3. Identification of the material that is claimed to be infringing and where it is located on the Site;";
    public static final String DIGITAL_MILLENIUM_4 = "4. Information reasonably sufficient to permit the Company to contact you, such as your address, telephone number, and e-mail address;";
    public static final String DIGITAL_MILLENIUM_5 = "5. A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or law; and";
    public static final String DIGITAL_MILLENIUM_6 = "6. A statement, made under penalty of perjury, that the above information is accurate, and that you are the copyright owner or are authorized to act on behalf of the owner.";

    public static final String DMC_OTHER = "The above information must be submitted to the following DMCA Agent:";
    public static final String DMC_OTHER_1 = "Designated Copyright Agent";
    public static final String DMC_OTHER_2 = "Yental Empire, LLC";
    public static final String DMC_OTHER_3 = "2885 Sanford Ave SW #28946, Grandville, MI 49418 broadcastsupport@rbenetwork.com (only DMCA notices will be accepted at this email address. All other inquiries or requests will be discarded)";

    public static final String REVISION_DATE ="This Agreement was last revised on November 21, 2014.";

}
